name: Orquestração Diária - Pipeline de Dados (Fase 5)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  pipeline_completa:
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1 - Checkout do Repositório
        uses: actions/checkout@v4

      - name: Passo 2 - Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Passo 3 - Instalar Dependências
        run: pip install google-cloud-bigquery pandas db-dtypes pandas-gbq

      - name: Passo 4 - Autenticação
        run: |
          cat << 'EOF' > credenciais_gcp.json
          ${{ secrets.GCP_CREDENTIALS }}
          EOF

      - name: Passo 5 - Ingestão Bronze
        run: python Modulo_4_Engenharia_Analytics_BQ/dia46_ingestao_bronze.py

      - name: Passo 6 - Limpeza Silver
        run: python Modulo_4_Engenharia_Analytics_BQ/dia47_limpeza_silver.py

      - name: Passo 7 - Camada Gold
        run: python Modulo_4_Engenharia_Analytics_BQ/dia50_gold.py

      - name: Passo 8 - Circuit Breaker
        run: python Modulo_4_Engenharia_Analytics_BQ/dia49_validacao_gold.py

      - name: Passo 9 - Limpeza de Segurança
        if: always()
        run: rm -f credenciais_gcp.json